---
galaxy_info:
  role_name: trustmebro_target
  author: KriyosArcane
  description: TrustMeBro victim machine setup for Ludus lab
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - security
    - redteam
dependencies: []
